# SPDX-FileCopyrightText: 2026 United Security Providers AG, Switzerland
#
# SPDX-License-Identifier: GPL-3.0-only

apiVersion: v1
kind: Secret
metadata:
  name: devuspacr
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkZXZ1c3ByZWdpc3RyeS5henVyZWNyLmlvIjp7ImF1dGgiOiJhMmxzYkdWeVkyOWtZVHBGV1M4NFUwTXpOMVphV2psVmF5OUtWa1Z5TkZrcmFrNUpVQ3RvWm1KbmIya3lhMXBJVDBOTGVUVXJRVU5TUWl0WFRYbGkifX19
type: kubernetes.io/dockerconfigjson
