apiVersion: v1
kind: Service
metadata:
  name: juiceshop-nodeport-access
  labels:
    app.kubernetes.io/instance: juiceshop-usp-core-waap
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: juiceshop-usp-core-waap
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30085
